timesteps: [250,600]
blur_kernel_size: 51
system_g: 3
c: 10

exp_setting: 'intra-subject'
eeg_backbone: 'EEGProjectLayerv2'
vision_backbone: 'ViT-bigG-14'
info: ''
name: "${exp_setting}_${eeg_backbone}_${vision_backbone}"
seed: 0


models:
  brain:
    target: "eeg_backbone.${eeg_backbone}"
    params:
        c_num: 17
        z_dim: 1280
        timesteps: ${timesteps}

data:
  subjects: ['sub-10']
  selected_ch: ['P7', 'P5', 'P3', 'P1','Pz', 'P2', 'P4', 'P6', 'P8', 'PO7', 'PO3', 'POz', 'PO4', 'PO8','O1', 'Oz', 'O2']

  model_type: ${vision_backbone}
  train_batch_size: 8
  val_batch_size: 200
  test_batch_size: 200
  uncertainty_aware: True
  mixco: True
  blur_type:
    target: inpating_data.FoveaBlur
    params:
          h: 224
          w: 224
          blur_kernel_size: ${blur_kernel_size}
          curve_type: exp
          system_g:  ${system_g}
  train_avg: True
  test_avg: True
  timesteps: ${timesteps}

train:
  epoch: 40
  optimizer: AdamW
  lr: 3e-4

save_dir: 'exp'