timesteps: [0,201]
exp_setting: 'intra-subject'
eeg_backbone: 'EEGProjectLayerv2'
vision_backbone: 'ViT-bigG-14'
info: ''
name: "${exp_setting}_${eeg_backbone}_${vision_backbone}"
seed: 0


models:
  brain:
    target: "eeg_backbone.${eeg_backbone}"
    params:
        c_num: 17
        z_dim: 1280
        timesteps: ${timesteps}

data:
  subjects: ['sub-10']
  selected_ch: ['P7', 'P5', 'P3', 'P1','Pz', 'P2', 'P4', 'P6', 'P8', 'PO7', 'PO3', 'POz', 'PO4', 'PO8','O1', 'Oz', 'O2']
  model_type: ${vision_backbone}
  train_batch_size: 1024
  val_batch_size: 200
  test_batch_size: 200
  uncertainty_aware: False
  mixco: True
  blur_type:
    target: inpating_data.DirectT
    params: {}
  train_avg: True
  test_avg: True
  timesteps: ${timesteps}

train:
  epoch: 50
  optimizer: AdamW
  lr: 1e-4

save_dir: 'exp'